計算アプリ課題完了
ay-amauchi/calc_app pull request #1
Opened 2022-10-13 11:23 UTC by ay-amauchi

ご確認よろしくお願いいたします。

2022-10-13 12:36 UTC, kazu-taka requested changes
@ay-amauchi 
2点ほど修正お願いします😊

2022-10-13 12:36 UTC, kazu-taka commented on app/Http/Controllers/calcs.php
> +class calcs extends Controller
@ay-amauchi 
一般的にはコントローラ名はアッパーキャメルケースの「CalcController」で表現するので、修正お願いします;bow;

2022-10-13 12:36 UTC, kazu-taka commented on routes/web.php
> +Route::get('/calcs/{value1}/{operator}/{value2}', [App\Http\Controllers\calcs::class, 'result']);
@ay-amauchi
コントローラ名修正時にこちらの修正をお願いします:bow:

2022-10-14 00:08 UTC, naoto1192 commented on app/Http/Controllers/calcs.php
> +class calcs extends Controller
カリキュラムに間違いがありましたので、今回に限ってはコントローラー名は`calcs`のままでOKです🙏

2022-10-14 00:10 UTC, naoto1192 commented
マージしてOKです👍
![97216](https://user-images.githubusercontent.com/98454350/195733870-6a301f9d-78d8-44cf-bd84-d89346a44567.jpeg)

2022-10-14 23:32 UTC, merged